In [45]:
import numpy as np
import math

In [2]:
moi = np.array([[4,5,6],[8,2,1],[4,4,3]])
toi = np.array([[4,5,6],[8,2.000001,1],[4,4,3]])
print(np.array_equal(moi,toi))

False


In [3]:
resolu = np.array([[1,2,3],[4,5,6],[0,8,7]])
indices = np.where(resolu == 0)
print(indices[0][0])

2


In [21]:
def trouverelement(matrice,element):
    for i in range(0,matrice.__len__()):
        for j in range (0,matrice[i].__len__()):
            if(matrice[i][j] == element):
                return [i,j]

In [31]:
def analyse(matrice,element):
    indices = trouverelement(matrice,0)
    ligne = indices[0]
    col = indices[1]
    fin = matrice.__len__()-1
    lesetat = []
    if(ligne!=0 and ligne!=fin and col!=0 and col!=fin ):
        lesetat = [1,-1,2,-2]
    elif(ligne == 0 and col == 0):
        lesetat = [-1,2]
    elif(ligne == 0 and col == fin):
        lesetat = [-1,-2]
    elif(ligne == fin and col == 0):
        lesetat = [1,2]
    elif(ligne == fin and col == fin):
        lesetat = [1,-2]
    elif(ligne == 0 and col > 0 and col < fin):
        lesetat = [-1,2,-2]
    elif(ligne == fin and col > 0 and col < fin):
        lesetat = [1,2,-2]
    elif(col == 0 and ligne > 0 and ligne<fin):
        lesetat = [-1,1,2]
    elif(col == fin and ligne > 0 and ligne<fin):
        lesetat = [-1,1,-2]

    while element in lesetat:
        lesetat.remove(element)
    return lesetat
    

In [48]:
def bouger(matrice,etat,position):
    newMatrice = np.array(matrice)
    ligne = position[0]
    col = position[1]
    indice = math.fabs(etat)
    if(indice == 2):
        maniere = int(etat/2)
        abouger = newMatrice[ligne][col+maniere]
        newMatrice[ligne][col+maniere] = 0
        newMatrice[ligne][col] = abouger
    elif(indice == 1):
        abouger = newMatrice[ligne-etat][col]
        newMatrice[ligne-etat][col] = 0
        newMatrice[ligne][col] = abouger
    return newMatrice

In [59]:
def verifie(tabMatrice, matrice):
        for mat in tabMatrice:
            val = np.array_equiv(mat,matrice)
            if(val == True):
                return 0
        return 1

In [64]:
resolue = np.array([[1,2,3],[6,5,0],[4,8,7]])
resolues = np.array([[0,2,3],[6,5,1],[4,8,7]])
resoluess = np.array([[1,2,3],[6,5,8],[4,0,7]])

list = []
list.append(resolue)
list.append(resolues)
list.append(resoluess)
print(verifie(list,resoluess))
for h in list:
    print(np.array_equal(h,np.array([[1,2,3],[6,5,8],[4,0,7]])))

0
False
False
True


In [58]:
from collections import deque
li = deque()
li.append(1)
li.append(2)
li.popleft()
li.append(3)
li.append(4)
li.popleft()
print(li)

deque([3, 4])


In [69]:
3 //2

1

In [70]:
3 // 4

0

In [86]:
def genereSolution(n):
        matrice = [[j+1+n*i for j in range(n)] for i in range(n)]
        matrice[n-1][n-1] = 0
        return np.array(matrice)

In [88]:
print(genereSolution(4))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15  0]]
